# Generated by Django 4.1.2 on 2022-10-21 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='type',
            field=models.CharField(choices=[('A', 'Article'), ('N', 'News')], default='N', max_length=1),
        ),
    ]
